server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location = /downloads/versao.json {
    add_header Cache-Control "no-store";
    default_type application/json;
  }
  location /downloads/ {
    types { application/vnd.android.package-archive apk; }
    add_header Cache-Control "no-cache";
  }
  location / { try_files $uri $uri/ =404; }
}
